version: "3"
services:
  web:
    image: mozilla/send:latest
    links:
      - redis
    ports:
      - "127.0.0.1:1443:1443"
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=production
      - FILE_DIR=/app/fs
      - ANON_MAX_DOWNLOADS=100
      - ANON_MAX_EXPIRE_SECONDS=604800
  redis:
    image: redis:alpine
